/*
 * LUSID API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.10.1388
 * Contact: info@finbourne.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.finbourne.lusid.model;

import com.finbourne.lusid.model.AggregateSpec;
import com.finbourne.lusid.model.ConfigurationRecipe;
import com.finbourne.lusid.model.OrderBySpec;
import com.finbourne.lusid.model.PropertyFilter;
import com.finbourne.lusid.model.ResourceId;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for AggregationRequest
 */
public class AggregationRequestTest {
    private final AggregationRequest model = new AggregationRequest();

    /**
     * Model tests for AggregationRequest
     */
    @Test
    public void testAggregationRequest() {
        // TODO: test AggregationRequest
    }

    /**
     * Test the property 'recipeId'
     */
    @Test
    public void recipeIdTest() {
        // TODO: test recipeId
    }

    /**
     * Test the property 'inlineRecipe'
     */
    @Test
    public void inlineRecipeTest() {
        // TODO: test inlineRecipe
    }

    /**
     * Test the property 'asAt'
     */
    @Test
    public void asAtTest() {
        // TODO: test asAt
    }

    /**
     * Test the property 'effectiveFrom'
     */
    @Test
    public void effectiveFromTest() {
        // TODO: test effectiveFrom
    }

    /**
     * Test the property 'effectiveAt'
     */
    @Test
    public void effectiveAtTest() {
        // TODO: test effectiveAt
    }

    /**
     * Test the property 'metrics'
     */
    @Test
    public void metricsTest() {
        // TODO: test metrics
    }

    /**
     * Test the property 'groupBy'
     */
    @Test
    public void groupByTest() {
        // TODO: test groupBy
    }

    /**
     * Test the property 'filters'
     */
    @Test
    public void filtersTest() {
        // TODO: test filters
    }

    /**
     * Test the property 'limit'
     */
    @Test
    public void limitTest() {
        // TODO: test limit
    }

    /**
     * Test the property 'sort'
     */
    @Test
    public void sortTest() {
        // TODO: test sort
    }

    /**
     * Test the property 'reportCcy'
     */
    @Test
    public void reportCcyTest() {
        // TODO: test reportCcy
    }

}
