/*
 * LUSID API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.10.1392
 * Contact: info@finbourne.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.finbourne.lusid.model;

import com.finbourne.lusid.model.AggregationOptions;
import com.finbourne.lusid.model.ConfigurationRecipe;
import com.finbourne.lusid.model.MarketDataKeyRule;
import com.finbourne.lusid.model.MarketOptions;
import com.finbourne.lusid.model.PricingOptions;
import com.finbourne.lusid.model.VendorModelRule;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for ConfigurationRecipeSnippet
 */
public class ConfigurationRecipeSnippetTest {
    private final ConfigurationRecipeSnippet model = new ConfigurationRecipeSnippet();

    /**
     * Model tests for ConfigurationRecipeSnippet
     */
    @Test
    public void testConfigurationRecipeSnippet() {
        // TODO: test ConfigurationRecipeSnippet
    }

    /**
     * Test the property 'aggregationOptions'
     */
    @Test
    public void aggregationOptionsTest() {
        // TODO: test aggregationOptions
    }

    /**
     * Test the property 'modelRules'
     */
    @Test
    public void modelRulesTest() {
        // TODO: test modelRules
    }

    /**
     * Test the property 'pricingOptions'
     */
    @Test
    public void pricingOptionsTest() {
        // TODO: test pricingOptions
    }

    /**
     * Test the property 'marketRules'
     */
    @Test
    public void marketRulesTest() {
        // TODO: test marketRules
    }

    /**
     * Test the property 'marketOptions'
     */
    @Test
    public void marketOptionsTest() {
        // TODO: test marketOptions
    }

    /**
     * Test the property 'recipe'
     */
    @Test
    public void recipeTest() {
        // TODO: test recipe
    }

}
