/*
 * LUSID API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.10.1392
 * Contact: info@finbourne.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.finbourne.lusid.model;

import com.finbourne.lusid.model.CreateUnitDefinition;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for CreateDataTypeRequest
 */
public class CreateDataTypeRequestTest {
    private final CreateDataTypeRequest model = new CreateDataTypeRequest();

    /**
     * Model tests for CreateDataTypeRequest
     */
    @Test
    public void testCreateDataTypeRequest() {
        // TODO: test CreateDataTypeRequest
    }

    /**
     * Test the property 'scope'
     */
    @Test
    public void scopeTest() {
        // TODO: test scope
    }

    /**
     * Test the property 'code'
     */
    @Test
    public void codeTest() {
        // TODO: test code
    }

    /**
     * Test the property 'typeValueRange'
     */
    @Test
    public void typeValueRangeTest() {
        // TODO: test typeValueRange
    }

    /**
     * Test the property 'displayName'
     */
    @Test
    public void displayNameTest() {
        // TODO: test displayName
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'valueType'
     */
    @Test
    public void valueTypeTest() {
        // TODO: test valueType
    }

    /**
     * Test the property 'acceptableValues'
     */
    @Test
    public void acceptableValuesTest() {
        // TODO: test acceptableValues
    }

    /**
     * Test the property 'unitSchema'
     */
    @Test
    public void unitSchemaTest() {
        // TODO: test unitSchema
    }

    /**
     * Test the property 'acceptableUnits'
     */
    @Test
    public void acceptableUnitsTest() {
        // TODO: test acceptableUnits
    }

}
