/*
 * LUSID API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.10.1380
 * Contact: info@finbourne.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.finbourne.lusid.model;

import com.finbourne.lusid.model.InlineValuationReconciliationRequest;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for InlineValuationsReconciliationRequest
 */
public class InlineValuationsReconciliationRequestTest {
    private final InlineValuationsReconciliationRequest model = new InlineValuationsReconciliationRequest();

    /**
     * Model tests for InlineValuationsReconciliationRequest
     */
    @Test
    public void testInlineValuationsReconciliationRequest() {
        // TODO: test InlineValuationsReconciliationRequest
    }

    /**
     * Test the property 'left'
     */
    @Test
    public void leftTest() {
        // TODO: test left
    }

    /**
     * Test the property 'right'
     */
    @Test
    public void rightTest() {
        // TODO: test right
    }

    /**
     * Test the property 'instrumentPropertyKeys'
     */
    @Test
    public void instrumentPropertyKeysTest() {
        // TODO: test instrumentPropertyKeys
    }

}
