/*
 * LUSID API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.10.1381
 * Contact: info@finbourne.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.finbourne.lusid.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for MarketOptions
 */
public class MarketOptionsTest {
    private final MarketOptions model = new MarketOptions();

    /**
     * Model tests for MarketOptions
     */
    @Test
    public void testMarketOptions() {
        // TODO: test MarketOptions
    }

    /**
     * Test the property 'defaultSupplier'
     */
    @Test
    public void defaultSupplierTest() {
        // TODO: test defaultSupplier
    }

    /**
     * Test the property 'defaultInstrumentCodeType'
     */
    @Test
    public void defaultInstrumentCodeTypeTest() {
        // TODO: test defaultInstrumentCodeType
    }

    /**
     * Test the property 'defaultScope'
     */
    @Test
    public void defaultScopeTest() {
        // TODO: test defaultScope
    }

    /**
     * Test the property 'attemptToInferMissingFx'
     */
    @Test
    public void attemptToInferMissingFxTest() {
        // TODO: test attemptToInferMissingFx
    }

    /**
     * Test the property 'manifestLevelOfDetail'
     */
    @Test
    public void manifestLevelOfDetailTest() {
        // TODO: test manifestLevelOfDetail
    }

}
