/*
 * LUSID API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.10.1388
 * Contact: info@finbourne.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.finbourne.lusid.model;

import com.finbourne.lusid.model.ModelSelection;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for PricingOptions
 */
public class PricingOptionsTest {
    private final PricingOptions model = new PricingOptions();

    /**
     * Model tests for PricingOptions
     */
    @Test
    public void testPricingOptions() {
        // TODO: test PricingOptions
    }

    /**
     * Test the property 'modelSelection'
     */
    @Test
    public void modelSelectionTest() {
        // TODO: test modelSelection
    }

    /**
     * Test the property 'useInstrumentTypeToDeterminePricer'
     */
    @Test
    public void useInstrumentTypeToDeterminePricerTest() {
        // TODO: test useInstrumentTypeToDeterminePricer
    }

    /**
     * Test the property 'allowAnyInstrumentsWithSecUidToPriceOffLookup'
     */
    @Test
    public void allowAnyInstrumentsWithSecUidToPriceOffLookupTest() {
        // TODO: test allowAnyInstrumentsWithSecUidToPriceOffLookup
    }

    /**
     * Test the property 'allowPartiallySuccessfulEvaluation'
     */
    @Test
    public void allowPartiallySuccessfulEvaluationTest() {
        // TODO: test allowPartiallySuccessfulEvaluation
    }

    /**
     * Test the property 'produceSeparateResultForLinearOtcLegs'
     */
    @Test
    public void produceSeparateResultForLinearOtcLegsTest() {
        // TODO: test produceSeparateResultForLinearOtcLegs
    }

    /**
     * Test the property 'enableUseOfCachedUnitResults'
     */
    @Test
    public void enableUseOfCachedUnitResultsTest() {
        // TODO: test enableUseOfCachedUnitResults
    }

    /**
     * Test the property 'windowValuationOnInstrumentStartEnd'
     */
    @Test
    public void windowValuationOnInstrumentStartEndTest() {
        // TODO: test windowValuationOnInstrumentStartEnd
    }

    /**
     * Test the property 'removeContingentCashflowsInPaymentDiary'
     */
    @Test
    public void removeContingentCashflowsInPaymentDiaryTest() {
        // TODO: test removeContingentCashflowsInPaymentDiary
    }

}
