/*
 * LUSID API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.10.1383
 * Contact: info@finbourne.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.finbourne.lusid.model;

import java.util.Objects;
import java.util.Arrays;
import com.finbourne.lusid.model.CorporateActionTransition;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;

/**
 * A corporate action
 */
@ApiModel(description = "A corporate action")

public class CorporateAction {
  public static final String SERIALIZED_NAME_CORPORATE_ACTION_CODE = "corporateActionCode";
  @SerializedName(SERIALIZED_NAME_CORPORATE_ACTION_CODE)
  private String corporateActionCode;

  public static final String SERIALIZED_NAME_DESCRIPTION = "description";
  @SerializedName(SERIALIZED_NAME_DESCRIPTION)
  private String description;

  public static final String SERIALIZED_NAME_ANNOUNCEMENT_DATE = "announcementDate";
  @SerializedName(SERIALIZED_NAME_ANNOUNCEMENT_DATE)
  private OffsetDateTime announcementDate;

  public static final String SERIALIZED_NAME_EX_DATE = "exDate";
  @SerializedName(SERIALIZED_NAME_EX_DATE)
  private OffsetDateTime exDate;

  public static final String SERIALIZED_NAME_RECORD_DATE = "recordDate";
  @SerializedName(SERIALIZED_NAME_RECORD_DATE)
  private OffsetDateTime recordDate;

  public static final String SERIALIZED_NAME_PAYMENT_DATE = "paymentDate";
  @SerializedName(SERIALIZED_NAME_PAYMENT_DATE)
  private OffsetDateTime paymentDate;

  public static final String SERIALIZED_NAME_TRANSITIONS = "transitions";
  @SerializedName(SERIALIZED_NAME_TRANSITIONS)
  private List<CorporateActionTransition> transitions = new ArrayList<>();

  public CorporateAction corporateActionCode(String corporateActionCode) {
    this.corporateActionCode = corporateActionCode;
    return this;
  }

   /**
   * The unique identifier of this corporate action
   * @return corporateActionCode
  **/
  @ApiModelProperty(required = true, value = "The unique identifier of this corporate action")
  public String getCorporateActionCode() {
    return corporateActionCode;
  }

  public void setCorporateActionCode(String corporateActionCode) {
    this.corporateActionCode = corporateActionCode;
  }

  public CorporateAction description(String description) {
    this.description = description;
    return this;
  }

   /**
   * 
   * @return description
  **/
  @ApiModelProperty(value = "")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public CorporateAction announcementDate(OffsetDateTime announcementDate) {
    this.announcementDate = announcementDate;
    return this;
  }

   /**
   * The announcement date of the corporate action
   * @return announcementDate
  **/
  @ApiModelProperty(value = "The announcement date of the corporate action")
  public OffsetDateTime getAnnouncementDate() {
    return announcementDate;
  }

  public void setAnnouncementDate(OffsetDateTime announcementDate) {
    this.announcementDate = announcementDate;
  }

  public CorporateAction exDate(OffsetDateTime exDate) {
    this.exDate = exDate;
    return this;
  }

   /**
   * The ex date of the corporate action
   * @return exDate
  **/
  @ApiModelProperty(value = "The ex date of the corporate action")
  public OffsetDateTime getExDate() {
    return exDate;
  }

  public void setExDate(OffsetDateTime exDate) {
    this.exDate = exDate;
  }

  public CorporateAction recordDate(OffsetDateTime recordDate) {
    this.recordDate = recordDate;
    return this;
  }

   /**
   * The record date of the corporate action
   * @return recordDate
  **/
  @ApiModelProperty(value = "The record date of the corporate action")
  public OffsetDateTime getRecordDate() {
    return recordDate;
  }

  public void setRecordDate(OffsetDateTime recordDate) {
    this.recordDate = recordDate;
  }

  public CorporateAction paymentDate(OffsetDateTime paymentDate) {
    this.paymentDate = paymentDate;
    return this;
  }

   /**
   * The payment date of the corporate action
   * @return paymentDate
  **/
  @ApiModelProperty(value = "The payment date of the corporate action")
  public OffsetDateTime getPaymentDate() {
    return paymentDate;
  }

  public void setPaymentDate(OffsetDateTime paymentDate) {
    this.paymentDate = paymentDate;
  }

  public CorporateAction transitions(List<CorporateActionTransition> transitions) {
    this.transitions = transitions;
    return this;
  }

  public CorporateAction addTransitionsItem(CorporateActionTransition transitionsItem) {
    if (this.transitions == null) {
      this.transitions = new ArrayList<>();
    }
    this.transitions.add(transitionsItem);
    return this;
  }

   /**
   * The transitions that result from this corporate action
   * @return transitions
  **/
  @ApiModelProperty(value = "The transitions that result from this corporate action")
  public List<CorporateActionTransition> getTransitions() {
    return transitions;
  }

  public void setTransitions(List<CorporateActionTransition> transitions) {
    this.transitions = transitions;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CorporateAction corporateAction = (CorporateAction) o;
    return Objects.equals(this.corporateActionCode, corporateAction.corporateActionCode) &&
        Objects.equals(this.description, corporateAction.description) &&
        Objects.equals(this.announcementDate, corporateAction.announcementDate) &&
        Objects.equals(this.exDate, corporateAction.exDate) &&
        Objects.equals(this.recordDate, corporateAction.recordDate) &&
        Objects.equals(this.paymentDate, corporateAction.paymentDate) &&
        Objects.equals(this.transitions, corporateAction.transitions);
  }

  @Override
  public int hashCode() {
    return Objects.hash(corporateActionCode, description, announcementDate, exDate, recordDate, paymentDate, transitions);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CorporateAction {\n");
    sb.append("    corporateActionCode: ").append(toIndentedString(corporateActionCode)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    announcementDate: ").append(toIndentedString(announcementDate)).append("\n");
    sb.append("    exDate: ").append(toIndentedString(exDate)).append("\n");
    sb.append("    recordDate: ").append(toIndentedString(recordDate)).append("\n");
    sb.append("    paymentDate: ").append(toIndentedString(paymentDate)).append("\n");
    sb.append("    transitions: ").append(toIndentedString(transitions)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
