/*
 * LUSID API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.10.1383
 * Contact: info@finbourne.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.finbourne.lusid.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.OffsetDateTime;

/**
 * FxOptionAllOf
 */

public class FxOptionAllOf {
  public static final String SERIALIZED_NAME_START_DATE = "startDate";
  @SerializedName(SERIALIZED_NAME_START_DATE)
  private OffsetDateTime startDate;

  public static final String SERIALIZED_NAME_OPTION_MATURITY_DATE = "optionMaturityDate";
  @SerializedName(SERIALIZED_NAME_OPTION_MATURITY_DATE)
  private OffsetDateTime optionMaturityDate;

  public static final String SERIALIZED_NAME_OPTION_SETTLEMENT_DATE = "optionSettlementDate";
  @SerializedName(SERIALIZED_NAME_OPTION_SETTLEMENT_DATE)
  private OffsetDateTime optionSettlementDate;

  public static final String SERIALIZED_NAME_IS_DELIVERY_NOT_CASH = "isDeliveryNotCash";
  @SerializedName(SERIALIZED_NAME_IS_DELIVERY_NOT_CASH)
  private Boolean isDeliveryNotCash;

  public static final String SERIALIZED_NAME_IS_CALL_NOT_PUT = "isCallNotPut";
  @SerializedName(SERIALIZED_NAME_IS_CALL_NOT_PUT)
  private Boolean isCallNotPut;

  public static final String SERIALIZED_NAME_STRIKE = "strike";
  @SerializedName(SERIALIZED_NAME_STRIKE)
  private Double strike;

  public static final String SERIALIZED_NAME_DOM_CCY = "domCcy";
  @SerializedName(SERIALIZED_NAME_DOM_CCY)
  private String domCcy;

  public static final String SERIALIZED_NAME_FGN_CCY = "fgnCcy";
  @SerializedName(SERIALIZED_NAME_FGN_CCY)
  private String fgnCcy;

  /**
   * Instrument type, must be property for JSON.
   */
  @JsonAdapter(InstrumentTypeEnum.Adapter.class)
  public enum InstrumentTypeEnum {
    QUOTEDSECURITY("QuotedSecurity"),
    
    INTERESTRATESWAP("InterestRateSwap"),
    
    FXFORWARD("FxForward"),
    
    EXOTIC("Exotic"),
    
    FXOPTION("FxOption"),
    
    CREDITDEFAULTSWAP("CreditDefaultSwap"),
    
    INTERESTRATESWAPTION("InterestRateSwaption"),
    
    BOND("Bond"),
    
    EQUITYOPTION("EquityOption"),
    
    UNKNOWN("Unknown");

    private String value;

    InstrumentTypeEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static InstrumentTypeEnum fromValue(String value) {
      for (InstrumentTypeEnum b : InstrumentTypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<InstrumentTypeEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final InstrumentTypeEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public InstrumentTypeEnum read(final JsonReader jsonReader) throws IOException {
        String value = jsonReader.nextString();
        return InstrumentTypeEnum.fromValue(value);
      }
    }
  }

  public static final String SERIALIZED_NAME_INSTRUMENT_TYPE = "instrumentType";
  @SerializedName(SERIALIZED_NAME_INSTRUMENT_TYPE)
  private InstrumentTypeEnum instrumentType;

  public FxOptionAllOf startDate(OffsetDateTime startDate) {
    this.startDate = startDate;
    return this;
  }

   /**
   * The start date of the option.
   * @return startDate
  **/
  @ApiModelProperty(required = true, value = "The start date of the option.")
  public OffsetDateTime getStartDate() {
    return startDate;
  }

  public void setStartDate(OffsetDateTime startDate) {
    this.startDate = startDate;
  }

  public FxOptionAllOf optionMaturityDate(OffsetDateTime optionMaturityDate) {
    this.optionMaturityDate = optionMaturityDate;
    return this;
  }

   /**
   * The maturity date of the option.
   * @return optionMaturityDate
  **/
  @ApiModelProperty(required = true, value = "The maturity date of the option.")
  public OffsetDateTime getOptionMaturityDate() {
    return optionMaturityDate;
  }

  public void setOptionMaturityDate(OffsetDateTime optionMaturityDate) {
    this.optionMaturityDate = optionMaturityDate;
  }

  public FxOptionAllOf optionSettlementDate(OffsetDateTime optionSettlementDate) {
    this.optionSettlementDate = optionSettlementDate;
    return this;
  }

   /**
   * The settlement date of the option.
   * @return optionSettlementDate
  **/
  @ApiModelProperty(required = true, value = "The settlement date of the option.")
  public OffsetDateTime getOptionSettlementDate() {
    return optionSettlementDate;
  }

  public void setOptionSettlementDate(OffsetDateTime optionSettlementDate) {
    this.optionSettlementDate = optionSettlementDate;
  }

  public FxOptionAllOf isDeliveryNotCash(Boolean isDeliveryNotCash) {
    this.isDeliveryNotCash = isDeliveryNotCash;
    return this;
  }

   /**
   * True of the option is settled in cash false if delivery.
   * @return isDeliveryNotCash
  **/
  @ApiModelProperty(required = true, value = "True of the option is settled in cash false if delivery.")
  public Boolean getIsDeliveryNotCash() {
    return isDeliveryNotCash;
  }

  public void setIsDeliveryNotCash(Boolean isDeliveryNotCash) {
    this.isDeliveryNotCash = isDeliveryNotCash;
  }

  public FxOptionAllOf isCallNotPut(Boolean isCallNotPut) {
    this.isCallNotPut = isCallNotPut;
    return this;
  }

   /**
   * True if the option is a call, false if the option is a put.
   * @return isCallNotPut
  **/
  @ApiModelProperty(required = true, value = "True if the option is a call, false if the option is a put.")
  public Boolean getIsCallNotPut() {
    return isCallNotPut;
  }

  public void setIsCallNotPut(Boolean isCallNotPut) {
    this.isCallNotPut = isCallNotPut;
  }

  public FxOptionAllOf strike(Double strike) {
    this.strike = strike;
    return this;
  }

   /**
   * The strike of the option.
   * @return strike
  **/
  @ApiModelProperty(required = true, value = "The strike of the option.")
  public Double getStrike() {
    return strike;
  }

  public void setStrike(Double strike) {
    this.strike = strike;
  }

  public FxOptionAllOf domCcy(String domCcy) {
    this.domCcy = domCcy;
    return this;
  }

   /**
   * The domestic currency of the FX.
   * @return domCcy
  **/
  @ApiModelProperty(required = true, value = "The domestic currency of the FX.")
  public String getDomCcy() {
    return domCcy;
  }

  public void setDomCcy(String domCcy) {
    this.domCcy = domCcy;
  }

  public FxOptionAllOf fgnCcy(String fgnCcy) {
    this.fgnCcy = fgnCcy;
    return this;
  }

   /**
   * The foreign currency of the FX.
   * @return fgnCcy
  **/
  @ApiModelProperty(required = true, value = "The foreign currency of the FX.")
  public String getFgnCcy() {
    return fgnCcy;
  }

  public void setFgnCcy(String fgnCcy) {
    this.fgnCcy = fgnCcy;
  }

  public FxOptionAllOf instrumentType(InstrumentTypeEnum instrumentType) {
    this.instrumentType = instrumentType;
    return this;
  }

   /**
   * Instrument type, must be property for JSON.
   * @return instrumentType
  **/
  @ApiModelProperty(required = true, value = "Instrument type, must be property for JSON.")
  public InstrumentTypeEnum getInstrumentType() {
    return instrumentType;
  }

  public void setInstrumentType(InstrumentTypeEnum instrumentType) {
    this.instrumentType = instrumentType;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FxOptionAllOf fxOptionAllOf = (FxOptionAllOf) o;
    return Objects.equals(this.startDate, fxOptionAllOf.startDate) &&
        Objects.equals(this.optionMaturityDate, fxOptionAllOf.optionMaturityDate) &&
        Objects.equals(this.optionSettlementDate, fxOptionAllOf.optionSettlementDate) &&
        Objects.equals(this.isDeliveryNotCash, fxOptionAllOf.isDeliveryNotCash) &&
        Objects.equals(this.isCallNotPut, fxOptionAllOf.isCallNotPut) &&
        Objects.equals(this.strike, fxOptionAllOf.strike) &&
        Objects.equals(this.domCcy, fxOptionAllOf.domCcy) &&
        Objects.equals(this.fgnCcy, fxOptionAllOf.fgnCcy) &&
        Objects.equals(this.instrumentType, fxOptionAllOf.instrumentType);
  }

  @Override
  public int hashCode() {
    return Objects.hash(startDate, optionMaturityDate, optionSettlementDate, isDeliveryNotCash, isCallNotPut, strike, domCcy, fgnCcy, instrumentType);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FxOptionAllOf {\n");
    sb.append("    startDate: ").append(toIndentedString(startDate)).append("\n");
    sb.append("    optionMaturityDate: ").append(toIndentedString(optionMaturityDate)).append("\n");
    sb.append("    optionSettlementDate: ").append(toIndentedString(optionSettlementDate)).append("\n");
    sb.append("    isDeliveryNotCash: ").append(toIndentedString(isDeliveryNotCash)).append("\n");
    sb.append("    isCallNotPut: ").append(toIndentedString(isCallNotPut)).append("\n");
    sb.append("    strike: ").append(toIndentedString(strike)).append("\n");
    sb.append("    domCcy: ").append(toIndentedString(domCcy)).append("\n");
    sb.append("    fgnCcy: ").append(toIndentedString(fgnCcy)).append("\n");
    sb.append("    instrumentType: ").append(toIndentedString(instrumentType)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
