/*
 * LUSID API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.10.1389
 * Contact: info@finbourne.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.finbourne.lusid.model;

import java.util.Objects;
import java.util.Arrays;
import com.finbourne.lusid.model.ValueTupleOfMarketDataKeyRuleToQuote;
import com.finbourne.lusid.model.ValueTupleOfMarketDataKeyRuleToStructuredMarketData;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * MarketDataManifest
 */

public class MarketDataManifest {
  public static final String SERIALIZED_NAME_QUOTES = "quotes";
  @SerializedName(SERIALIZED_NAME_QUOTES)
  private Map<String, ValueTupleOfMarketDataKeyRuleToQuote> quotes = new HashMap<>();

  public static final String SERIALIZED_NAME_STRUCTURED_MARKET_DATA = "structuredMarketData";
  @SerializedName(SERIALIZED_NAME_STRUCTURED_MARKET_DATA)
  private Map<String, ValueTupleOfMarketDataKeyRuleToStructuredMarketData> structuredMarketData = new HashMap<>();

  public MarketDataManifest quotes(Map<String, ValueTupleOfMarketDataKeyRuleToQuote> quotes) {
    this.quotes = quotes;
    return this;
  }

  public MarketDataManifest putQuotesItem(String key, ValueTupleOfMarketDataKeyRuleToQuote quotesItem) {
    if (this.quotes == null) {
      this.quotes = new HashMap<>();
    }
    this.quotes.put(key, quotesItem);
    return this;
  }

   /**
   * Get quotes
   * @return quotes
  **/
  @ApiModelProperty(value = "")
  public Map<String, ValueTupleOfMarketDataKeyRuleToQuote> getQuotes() {
    return quotes;
  }

  public void setQuotes(Map<String, ValueTupleOfMarketDataKeyRuleToQuote> quotes) {
    this.quotes = quotes;
  }

  public MarketDataManifest structuredMarketData(Map<String, ValueTupleOfMarketDataKeyRuleToStructuredMarketData> structuredMarketData) {
    this.structuredMarketData = structuredMarketData;
    return this;
  }

  public MarketDataManifest putStructuredMarketDataItem(String key, ValueTupleOfMarketDataKeyRuleToStructuredMarketData structuredMarketDataItem) {
    if (this.structuredMarketData == null) {
      this.structuredMarketData = new HashMap<>();
    }
    this.structuredMarketData.put(key, structuredMarketDataItem);
    return this;
  }

   /**
   * Get structuredMarketData
   * @return structuredMarketData
  **/
  @ApiModelProperty(value = "")
  public Map<String, ValueTupleOfMarketDataKeyRuleToStructuredMarketData> getStructuredMarketData() {
    return structuredMarketData;
  }

  public void setStructuredMarketData(Map<String, ValueTupleOfMarketDataKeyRuleToStructuredMarketData> structuredMarketData) {
    this.structuredMarketData = structuredMarketData;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MarketDataManifest marketDataManifest = (MarketDataManifest) o;
    return Objects.equals(this.quotes, marketDataManifest.quotes) &&
        Objects.equals(this.structuredMarketData, marketDataManifest.structuredMarketData);
  }

  @Override
  public int hashCode() {
    return Objects.hash(quotes, structuredMarketData);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MarketDataManifest {\n");
    sb.append("    quotes: ").append(toIndentedString(quotes)).append("\n");
    sb.append("    structuredMarketData: ").append(toIndentedString(structuredMarketData)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
