/*
 * LUSID API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.10.1388
 * Contact: info@finbourne.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.finbourne.lusid.model;

import java.util.Objects;
import java.util.Arrays;
import com.finbourne.lusid.model.Property;
import com.finbourne.lusid.model.Version;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * Person
 */

public class Person {
  public static final String SERIALIZED_NAME_HREF = "href";
  @SerializedName(SERIALIZED_NAME_HREF)
  private String href;

  public static final String SERIALIZED_NAME_LUSID_PERSON_ID = "lusidPersonId";
  @SerializedName(SERIALIZED_NAME_LUSID_PERSON_ID)
  private String lusidPersonId;

  public static final String SERIALIZED_NAME_IDENTIFIERS = "identifiers";
  @SerializedName(SERIALIZED_NAME_IDENTIFIERS)
  private Map<String, Property> identifiers = new HashMap<>();

  public static final String SERIALIZED_NAME_PROPERTIES = "properties";
  @SerializedName(SERIALIZED_NAME_PROPERTIES)
  private Map<String, List<Property>> properties = new HashMap<>();

  public static final String SERIALIZED_NAME_VERSION = "version";
  @SerializedName(SERIALIZED_NAME_VERSION)
  private Version version = null;

   /**
   * The specifc Uniform Resource Identifier (URI) for this resource at the requested effective and asAt datetime.
   * @return href
  **/
  @ApiModelProperty(value = "The specifc Uniform Resource Identifier (URI) for this resource at the requested effective and asAt datetime.")
  public String getHref() {
    return href;
  }

   /**
   * The unique LUSID Person Identifier (LUPID) of the Person.
   * @return lusidPersonId
  **/
  @ApiModelProperty(value = "The unique LUSID Person Identifier (LUPID) of the Person.")
  public String getLusidPersonId() {
    return lusidPersonId;
  }

  public Person identifiers(Map<String, Property> identifiers) {
    this.identifiers = identifiers;
    return this;
  }

  public Person putIdentifiersItem(String key, Property identifiersItem) {
    if (this.identifiers == null) {
      this.identifiers = new HashMap<>();
    }
    this.identifiers.put(key, identifiersItem);
    return this;
  }

   /**
   * Unique client-defined identifiers of the Person.
   * @return identifiers
  **/
  @ApiModelProperty(value = "Unique client-defined identifiers of the Person.")
  public Map<String, Property> getIdentifiers() {
    return identifiers;
  }

  public void setIdentifiers(Map<String, Property> identifiers) {
    this.identifiers = identifiers;
  }

  public Person properties(Map<String, List<Property>> properties) {
    this.properties = properties;
    return this;
  }

  public Person putPropertiesItem(String key, List<Property> propertiesItem) {
    if (this.properties == null) {
      this.properties = new HashMap<>();
    }
    this.properties.put(key, propertiesItem);
    return this;
  }

   /**
   * A set of properties associated to the Person. There can be multiple properties associated with a property key.
   * @return properties
  **/
  @ApiModelProperty(value = "A set of properties associated to the Person. There can be multiple properties associated with a property key.")
  public Map<String, List<Property>> getProperties() {
    return properties;
  }

  public void setProperties(Map<String, List<Property>> properties) {
    this.properties = properties;
  }

  public Person version(Version version) {
    this.version = version;
    return this;
  }

   /**
   * Get version
   * @return version
  **/
  @ApiModelProperty(value = "")
  public Version getVersion() {
    return version;
  }

  public void setVersion(Version version) {
    this.version = version;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Person person = (Person) o;
    return Objects.equals(this.href, person.href) &&
        Objects.equals(this.lusidPersonId, person.lusidPersonId) &&
        Objects.equals(this.identifiers, person.identifiers) &&
        Objects.equals(this.properties, person.properties) &&
        Objects.equals(this.version, person.version);
  }

  @Override
  public int hashCode() {
    return Objects.hash(href, lusidPersonId, identifiers, properties, version);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Person {\n");
    sb.append("    href: ").append(toIndentedString(href)).append("\n");
    sb.append("    lusidPersonId: ").append(toIndentedString(lusidPersonId)).append("\n");
    sb.append("    identifiers: ").append(toIndentedString(identifiers)).append("\n");
    sb.append("    properties: ").append(toIndentedString(properties)).append("\n");
    sb.append("    version: ").append(toIndentedString(version)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
