/*
 * LUSID API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.10.1381
 * Contact: info@finbourne.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.finbourne.lusid.model;

import java.util.Objects;
import java.util.Arrays;
import com.finbourne.lusid.model.AccessMetadataValue;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * UpsertPortfolioGroupAccessMetadataRequest
 */

public class UpsertPortfolioGroupAccessMetadataRequest {
  public static final String SERIALIZED_NAME_METADATA = "metadata";
  @SerializedName(SERIALIZED_NAME_METADATA)
  private List<AccessMetadataValue> metadata = new ArrayList<>();

  public UpsertPortfolioGroupAccessMetadataRequest metadata(List<AccessMetadataValue> metadata) {
    this.metadata = metadata;
    return this;
  }

  public UpsertPortfolioGroupAccessMetadataRequest addMetadataItem(AccessMetadataValue metadataItem) {
    this.metadata.add(metadataItem);
    return this;
  }

   /**
   * The access control metadata to assign to portfolio groups that match the identifier
   * @return metadata
  **/
  @ApiModelProperty(required = true, value = "The access control metadata to assign to portfolio groups that match the identifier")
  public List<AccessMetadataValue> getMetadata() {
    return metadata;
  }

  public void setMetadata(List<AccessMetadataValue> metadata) {
    this.metadata = metadata;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UpsertPortfolioGroupAccessMetadataRequest upsertPortfolioGroupAccessMetadataRequest = (UpsertPortfolioGroupAccessMetadataRequest) o;
    return Objects.equals(this.metadata, upsertPortfolioGroupAccessMetadataRequest.metadata);
  }

  @Override
  public int hashCode() {
    return Objects.hash(metadata);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UpsertPortfolioGroupAccessMetadataRequest {\n");
    sb.append("    metadata: ").append(toIndentedString(metadata)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
