version: "3"

services:

  lusid-sdk-java-preview-test:
    build: .
    container_name: lusid-sdk-java-preview-test
    image: finbourne/lusid-sdk-java-preview-test
    environment:
      - FBN_TOKEN_URL
      - FBN_USERNAME
      - FBN_PASSWORD
      - FBN_CLIENT_ID
      - FBN_CLIENT_SECRET
      - FBN_LUSID_API_URL
      - FBN_APP_NAME
    volumes:
      - .:/usr/src