version: "3"

services:

  lusid-sdk-java-preview-test:
    build: .
    container_name: lusid-sdk-java-preview-test
    image: finbourne/lusid-sdk-java-preview-test
    environment:
          - FBN_LUSID_API_URL
    volumes:
      - .:/usr/src